kubernetes:
  configPath: D:/config
server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://192.168.18.150:3306/devops
    username: root
    password: Qi09rNpOXYbiJoGAeGfdUgtLmmik/zMSFtCx1/p9Z0pROmfr0oh86QzTra6qntihb/IjSuTjV+l21PPYLcYKMQ==
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAKDgF2oSEwgYTHXdDxT7d/pATlVijpTGv8yam4h+P4E852LSLaZDsoVX3lGSc+PecRPHESn5A0HMnCVpKufUlO0CAwEAAQ==
    connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000;config.decrypt=true;config.decrypt.key=${spring.datasource.publicKey}
    filter:
      config:
        enable: true
    min-idle: 10
    max-active: 100
    initial-size: 10
    max-wait: 10
    timeBetweenEvictionRunsMillis: 60000
    testOnBorrow: false
    testOnReturn: false
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 1 FROM DUAL
    test-while-idle: true
  security:
    user:
      name: handong
      password: hdlmx522104

#logging:
#  config: src/main/resources/logback.xml
#  level: trace
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:/cn/hdlmx/devops/mapper/*.xml
